# Generated by Django 5.0.3 on 2024-04-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneByteFood', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
