# Generated by Django 5.0.3 on 2024-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_signup_data_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_data',
            name='staff_status',
            field=models.BooleanField(default=True),
        ),
    ]
