# Generated by Django 5.0.3 on 2024-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_signup_data_staff_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_data',
            name='staff_status',
        ),
        migrations.AddField(
            model_name='signup_data',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
