# Generated by Django 5.0.3 on 2024-05-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByteFood', '0004_alter_reservation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.CharField(default='1', max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
    ]
