# Generated by Django 5.0.4 on 2024-05-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByteFood', '0006_birthdaythemereservation_fooditem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.URLField(default='default_image_url'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
