# Generated by Django 5.0.4 on 2024-05-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneByteFood', '0007_cartitem_image_url_cartitem_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthdayThemeReservation',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
    ]
