# Generated by Django 5.0.4 on 2024-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByteFood', '0008_delete_birthdaythemereservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='birthday_theme_reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('num_people', models.IntegerField()),
                ('comments', models.TextField()),
                ('payment_made', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('theme', models.CharField(default='unicorn', max_length=50)),
            ],
        ),
    ]
